apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5VENDQWQyZ0F3SUJBZ0lSQU80VExBRE9vMDNXdlZzQkJzL0t6VHd3RFFZSktvWklodmNOQVFFTEJRQXcKSWpFZ01CNEdBMVVFQXd3WGEzVmlaWEp1WlhSbGN5MWpiSFZ6ZEdWeUxUSXpNVEl3SGhjTk1qTXhNREl5TVRVMQpOVEU1V2hjTk1qZ3hNREl4TVRVMU5URTVXakFpTVNBd0hnWURWUVFEREJkcmRXSmxjbTVsZEdWekxXTnNkWE4wClpYSXRNak14TWpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSnBPSE1URU5tN3YKUHRtQWNZVGNWeFQ1K0wvdWJWczBJWi8ySlk4bWh0WlZTSHd1OHdQU1dtQ2U2eEZ6WjhtOXFxZ0kramVaZnZYWApEM2MwdTRoTVYwUm1xaVhZRWRzQVJMTXUvaDJGOHRZbFRSSXAwa1hkNVZNSVdEUHlXUU5JNDZmZ1VCOU5MV0FSCmJISzFETlg3T0dBR2NwcE5aWTJ4TGp4NlB0VmZmaWc0VVhTWXhUdDNwYUd0VW8za2xiWTlUb3QyVlp4VUwrS0MKZnhiMXl5ejhLcnd5UmpCZGlqNnJPLy9VRzEvQ2Z1T3RjZk1yYkZ5cjdNZklRdkdNb1paTGxtNTV0N1BJNTNOOApLTDZMNFI3cEdJR243VjVCamc3Rm9yMmVsUVJ4eHVVYWY4M1FGSkdQSkJDT1VPeUZnMkU4TjV1bkhZZmppVWRtCjh4bXNuOHlZa0ZFQ0F3RUFBYU1tTUNRd0VnWURWUjBUQVFIL0JBZ3dCZ0VCL3dJQkFEQU9CZ05WSFE4QkFmOEUKQkFNQ0FnUXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSExEaVp3WldIRDhiSVlTR1Q2dkVTNjgzZm5kalN3cgp6ckFiaktLRXZlVHFaL1UvNjJFRWVBK0FLMGlkZGd1OWg0YmQ2UU5nR0NIRjUvYlBQdkhqTTJqVW1XWVhIY3RkCmhmZmpSR2RUaHNQdStYMzlMMzhOQ1ROaUNnWnNOUXVZSEZVTy8rbEpUZW9BZDg1aFpLVVRkbzNDZys3cG9MWFcKUjlNV0RRK21ybnR3dUp0OFJGdnpxNXFZTExkNys2ZFU3Q3laSDBFeGYrRzNFSkNhalNsTC9jWXhnREJEbk50ZAp1Y2lIZ2RiOUlJT3NDaEtXakV1MDl2bXVVMEdMTExnSDFjZ2JXN25pa1ErcWJHNEg4T2FiVzlQOUpINHdiTlBvCnBVM2c3V24zdjdGL1VFRHc4SlZiMkZ4NHdCOEdCRVFUTGN3dGplUjlHRk1BU0hJWVVKeUV0WFk9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://95.163.182.229:6443
  name: kubernetes-cluster-2312
contexts:
- context:
    cluster: kubernetes-cluster-2312
    user: kubernetes-cluster-2312
  name: default/kubernetes-cluster-2312
current-context: default/kubernetes-cluster-2312
kind: Config
preferences: {}
users:
- name: kubernetes-cluster-2312
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: client-keystone-auth
      env:
      - name: "OS_AUTH_URL"
        value: "https://infra.mail.ru:35357/v3/"
      - name: "OS_USERNAME"
        value: "spyon.alex@yandex.ru"
      - name: "OS_PROJECT_ID"
        value: "cc205d33a5c44efa8d376e0dbabb49e3"
      - name: "OS_DOMAIN_NAME"
        value: "users"
      interactiveMode: IfAvailable
      provideClusterInfo: false