name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker compose build
    - name: Run container
      run: docker compose up -d

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      # - name: Install postgreSQL
      - name: Run tests
        run: python -m unittest ./webapp/tests/test_api_status.py
