name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker compose build
    - name: Run container
      run: docker compose up -d

  test:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
    - uses: actions/checkout@v3
    - name: Build and run tests the Docker image
      run: docker-compose -f test_docker-compose.yml up --build --abort-on-container-exit --exit-code-from flask_web
      
  deploy:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
    - uses: actions/checkout@v3
    - name: Trigger deploy via Render API
      env:
        deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
      run:
          curl "$deploy_url"
